/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

/**
 *
 * @author Kuroi-Tenshi
 */
public class MenuCV extends javax.swing.JDialog {
    private InterfaceGraphique fenetre;
    private Personne info;
    private TitreCV fenTitre;
    private MenuXP fenMenuXP;
    private MenuForm fenMenuForm;
    private MenuInfo fenMenuInfo;
    private MenuLangue fenMenuLangue;
    private MenuHobbie fenMenuHobbie;
    /**
     * Creates new form MenuCV
     */
    public MenuCV(java.awt.Frame parent, boolean modal, Personne gens) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //modal==true signifie que l'on ne peut pas revenir 
        //sur la precedente fenêtre dans fermer connexion
        this.setModal(true);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre=(InterfaceGraphique)parent;
        //initialisation données de la page et du paramettre info
        
        this.info = gens;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTitre = new javax.swing.JButton();
        jButtonXP = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jButtonForm = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jButtonLangue = new javax.swing.JButton();
        jButtonHobbie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu modification CV");

        jButtonTitre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonTitre.setText("Modifier Titre");
        jButtonTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTitreActionPerformed(evt);
            }
        });

        jButtonXP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonXP.setText("Experience Pro");
        jButtonXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXPActionPerformed(evt);
            }
        });

        jButtonRetour.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jButtonForm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonForm.setText("Formation");
        jButtonForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormActionPerformed(evt);
            }
        });

        jButtonInfo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonInfo.setText("Informatique");
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });

        jButtonLangue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonLangue.setText("Langue");
        jButtonLangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLangueActionPerformed(evt);
            }
        });

        jButtonHobbie.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonHobbie.setText("Hobbies");
        jButtonHobbie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHobbieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonForm, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHobbie, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonXP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonForm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHobbie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTitreActionPerformed
        fenTitre =new TitreCV(this, true,info);
        this.fenTitre.setVisible(true);
    }//GEN-LAST:event_jButtonTitreActionPerformed

    private void jButtonXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXPActionPerformed
        fenMenuXP = new MenuXP(this, true,info);
        this.fenMenuXP.setVisible(true);
    }//GEN-LAST:event_jButtonXPActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButtonFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormActionPerformed
        fenMenuForm = new MenuForm(this, true, info);
        this.fenMenuForm.setVisible(true);
    }//GEN-LAST:event_jButtonFormActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        fenMenuInfo = new MenuInfo(this, true, info);
        this.fenMenuInfo.setVisible(true);
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonLangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLangueActionPerformed
        fenMenuLangue = new MenuLangue(this, true, info);
        this.fenMenuLangue.setVisible(true);
    }//GEN-LAST:event_jButtonLangueActionPerformed

    private void jButtonHobbieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHobbieActionPerformed
        fenMenuHobbie = new MenuHobbie(this, true, info);
        this.fenMenuHobbie.setVisible(true);
    }//GEN-LAST:event_jButtonHobbieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuCV dialog = new MenuCV(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForm;
    private javax.swing.JButton jButtonHobbie;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonLangue;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonTitre;
    private javax.swing.JButton jButtonXP;
    // End of variables declaration//GEN-END:variables
}
